# CMake generated Testfile for 
# Source directory: /Users/akanksha/Desktop/files/Data Science Projects/Photo Editor/opencv-python-4.5.3.56/opencv/modules
# Build directory: /Users/akanksha/Desktop/files/Data Science Projects/Photo Editor/opencv-python-4.5.3.56/_skbuild/macosx-10.16-x86_64-3.7/cmake-build/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(".firstpass/calib3d")
subdirs(".firstpass/core")
subdirs(".firstpass/dnn")
subdirs(".firstpass/features2d")
subdirs(".firstpass/flann")
subdirs(".firstpass/gapi")
subdirs(".firstpass/highgui")
subdirs(".firstpass/imgcodecs")
subdirs(".firstpass/imgproc")
subdirs(".firstpass/java")
subdirs(".firstpass/js")
subdirs(".firstpass/ml")
subdirs(".firstpass/objc")
subdirs(".firstpass/objdetect")
subdirs(".firstpass/photo")
subdirs(".firstpass/python")
subdirs(".firstpass/stitching")
subdirs(".firstpass/ts")
subdirs(".firstpass/video")
subdirs(".firstpass/videoio")
subdirs(".firstpass/world")
subdirs("core")
subdirs("flann")
subdirs("imgproc")
subdirs("ml")
subdirs("photo")
subdirs("python_tests")
subdirs("dnn")
subdirs("features2d")
subdirs("imgcodecs")
subdirs("videoio")
subdirs("calib3d")
subdirs("highgui")
subdirs("objdetect")
subdirs("stitching")
subdirs("video")
subdirs("gapi")
subdirs("java_bindings_generator")
subdirs("js_bindings_generator")
subdirs("objc_bindings_generator")
subdirs("python_bindings_generator")
subdirs("python3")
